const groupTableData = [
  {
    groupId: 1,
    groupName: "Green, Stark and Moore",
    phone: "312-656-0397",
    email: "vjagson0@tmall.com",
    address: "2452 Maywood Point",
    contactFirstName: "Valenka",
    contactLastName: "Jagson",
    city: "Chicago",
    state: "Illinois",
  },
  {
    groupId: 2,
    groupName: "Langworth, Hauck and Skiles",
    phone: "760-450-4097",
    email: "closel1@fotki.com",
    address: "7 Oak Avenue",
    contactFirstName: "Connie",
    contactLastName: "Losel",
    city: "Carlsbad",
    state: "California",
  },
  {
    groupId: 3,
    groupName: "Hegmann LLC",
    phone: "213-934-1840",
    email: "jtrain2@abc.net.au",
    address: "8040 Green Drive",
    contactFirstName: "Jacinthe",
    contactLastName: "Train",
    city: "Los Angeles",
    state: "California",
  },
  {
    groupId: 4,
    groupName: "Dach Group",
    phone: "801-303-8457",
    email: "emeldon3@marriott.com",
    address: "52643 Northport Road",
    contactFirstName: "Emogene",
    contactLastName: "Meldon",
    city: "Salt Lake City",
    state: "Utah",
  },
  {
    groupId: 5,
    groupName: "Bauch, Johns and Rath",
    phone: "573-276-2848",
    email: "cgibbeson4@ning.com",
    address: "63782 Westend Circle",
    contactFirstName: "Carleton",
    contactLastName: "Gibbeson",
    city: "Columbia",
    state: "Missouri",
  },
  {
    groupId: 6,
    groupName: "Pfannerstill, Treutel and Tromp",
    phone: "480-747-3236",
    email: "bclucas5@acquirethisname.com",
    address: "4231 Holmberg Crossing",
    contactFirstName: "Barbara",
    contactLastName: "Clucas",
    city: "Chandler",
    state: "Arizona",
  },
  {
    groupId: 7,
    groupName: "Orn Inc",
    phone: "608-426-6482",
    email: "ewaterworth6@admin.ch",
    address: "9 Oakridge Avenue",
    contactFirstName: "Eugenius",
    contactLastName: "Waterworth",
    city: "Madison",
    state: "Wisconsin",
  },
  {
    groupId: 8,
    groupName: "Monahan Inc",
    phone: "309-725-8653",
    email: "nmanktelow7@4shared.com",
    address: "4249 Ludington Park",
    contactFirstName: "Nedi",
    contactLastName: "Manktelow",
    city: "Peoria",
    state: "Illinois",
  },
  {
    groupId: 9,
    groupName: "Schaefer, Rodriguez and Wisozk",
    phone: "315-265-7969",
    email: "tdriscoll8@usgs.gov",
    address: "52 Oneill Terrace",
    contactFirstName: "Terese",
    contactLastName: "Driscoll",
    city: "Syracuse",
    state: "New York",
  },
  {
    groupId: 10,
    groupName: "Ziemann-Dach",
    phone: "754-804-2357",
    email: "sstathor9@washingtonpost.com",
    address: "69 Burning Wood Parkway",
    contactFirstName: "Shena",
    contactLastName: "Stathor",
    city: "Fort Lauderdale",
    state: "Florida",
  },
];
export default groupTableData;
